language: node_js
node_js:
  - "10"
before_install: npm install -g greenkeeper-lockfile
addons:
  chrome: stable
sudo: required
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"